language: python

python:
  - "3.8"

arch:
  - amd64
  - arm64

install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
  - hg --version
  - pip install tox-travis
  - uname -m

script: tox
